name: Go

on:
  push:
    branches: [ main ]
  schedule:
   - cron : "0 9 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
    
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: go mod tidy 
    - run: go mod download
    - run: go run main.go
    
    # 提交
    - name: Commit files
      run: |
        git add README.md
        git config --local user.email "709124735@qq.com"
        git config --local user.name "lziqi"
        git commit --allow-empty -m "Update today's weather on $(date)" -a
    
    # Push
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


